# Generated by Django 3.1.1 on 2020-12-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_auto_20201212_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='City', max_length=50, verbose_name='City'),
        ),
    ]
